import React from 'react';
import { notFound } from "next/navigation";
import { appConfig } from "@/app/utils/config";
import ProductSameCategory from "@/app/components/products/ProductSameCategory";
import Spacer from "@/app/components/common/Spacer";

export async function generateMetadata({ params }) {
    const { id } = params;
    return {
        title: `${id}'li ürün`,
        description: "Generated by create next app",
    };
}

const ProductDetailPage = async ({ params }) => {
    const { id } = params;

    if (!id) {
        throw new Error(`Product with id ${id} not found.`);
    }

    const productRes = await fetch(`${appConfig.apiURL}/products/${id}`);
    const allProductsRes = await fetch(`${appConfig.apiURL}/products`);

    const [product, allProducts] = await Promise.all([
        productRes.json(),
        allProductsRes.json(),
    ]);

    if (!productRes.ok || !product || Object.keys(product).length === 0) {
        notFound();
    }

    return (
        <div className="flex flex-col min-h-screen">
            <Spacer height={65}/>
            {/* Product Detail Section */}
            <div className="flex flex-col gap-4  lg:flex-row items-center justify-center p-6">
                {/* Image */}
                <div className="md:flex-1 min-h-[350px] max-md:max-h-[350px] md:max-h-[500px] lg:h-auto shadow-xl w-full rounded-xl overflow-hidden">
                    <img
                        src={product.image}
                        alt={product.title}
                        className="w-full h-full object-center object-cover"
                    />
                </div>

                {/* Product Info */}
                <div className="md:flex-1 w-full flex flex-col gap-4">
                    <div className="flex lg:flex-col justify-between w-full">
                        <div>
                            <h2 className="text-xl font-bold text-gray-800">{product.title}</h2>
                            <h3 className="text-lg font-semibold text-gray-600">{product.category}</h3>
                        </div>
                        <p className="text-lg font-semibold text-amber-500">${product.price}</p>
                    </div>

                    <p className="text-gray-700">{product.description}</p>
                </div>
            </div>

            {/* Related Products */}
            <div className="px-4 py-6">
                <ProductSameCategory products={allProducts} />
            </div>

            <Spacer />
        </div>
    );
};

export default ProductDetailPage;
