import React from 'react';

export const metadata = {
    title: "About",
    description: "Generated by create next app",
};

const AboutPage = () => {
    return (
        <div>
            <div className={'h-[65px]'}></div>
            About Page
        </div>
    );
};

export default AboutPage;
