import {Exo} from "next/font/google";
import "./globals.css"




const geistExo = Exo({
  variable: "--font-exo",
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"   >
      <body
        className={`${geistExo.variable} `}
      >
        {children}
      </body>
    </html>
  );
}
