import "./globals.css"
import {exo, roboto} from "@/app/utils/fonts";

export const metadata = {
    title: {template: "Cosmo Shop | %s", default: "Cosmo Shop"},
    description: "Generated by create next app",
    keywords: ['Next.js', 'React', 'JavaScript'],
    authors: [{ name: 'Mustafa Keser' }],
    creator: "Mustafa Keser",
    publisher: 'Mustafa Keser',
};


export default function RootLayout({children}) {
    return (
        <html lang="en" >
        <body
            className={`${exo.variable} ${roboto.variable}`}
        >
        {children}
        </body>
        </html>
    );
}
