import React from 'react';

export async function generateMetadata({ params }) {

    const { categoryId, itemId } = await params;

    return {
        title: `${categoryId} - ${itemId} Id'ye ait urun`,
        description: "Generated by create next app",
    }
}

const page = async ({params}) => {

    const { categoryId, itemId } = await params;

    console.log(categoryId)
    console.log(itemId);

    return (
        <div>

            <div className='h-[65px]'></div>
            <p className='capitalize font-semibold text-lg'>{categoryId} Kategori</p>
            <p>{itemId}'li urun</p>
        </div>
    );
};

export default page;
