import React from 'react';

export const metadata = {
    title: "Contact",
    description: "Generated by create next app",
};

const Contact = () => {
    return (
        <div>
            <div className="h-[65px]"></div>
            Contact page
        </div>
    );
};

export default Contact;
