import React from 'react';
import PageHeader from "@/app/components/PageHeader";
import Spacer from "@/app/components/common/Spacer";
import {appConfig} from "@/app/utils/config";
import ProductList from "@/app/components/ProductList";

export const metadata = {
    title: "Products",
    description: "Generated by create next app",
};

const ProductsPage = async () => {

    const res = await fetch(`${appConfig.apiURL}/products`);
    const products = await res.json();

    console.log(products)

    return (
        <div className='w-full'>
            <Spacer height={65}/>
            <PageHeader title={"Products "}/>
            <Spacer height={40}/>

            <div className="product px-10 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4 gap-y-16">
                {
                    products.map((product) => (

                        <ProductList key={product.title} product={product} />

                    ))
                }
            </div>

        </div>
    );
};

export default ProductsPage;
